# Generated by Django 2.2.4 on 2019-08-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0002_auto_20190812_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='event_type',
            field=models.CharField(default='OBJECT', help_text='The type of EPCIS event to create.', max_length=20, verbose_name='Event Type'),
        ),
    ]
