# Generated by Django 2.2.4 on 2019-08-13 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0003_transaction_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 21, 6, 47, 704751), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
