# Generated by Django 2.2.4 on 2019-08-13 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0004_auto_20190813_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='end_point',
            field=models.ForeignKey(blank=True, help_text='A prtocol-specific endpoint defining where any output data will be sent.', null=True, on_delete=django.db.models.deletion.PROTECT, to='quartet_output.EndPoint', verbose_name='End Point'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 21, 9, 55, 9162), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
