# Generated by Django 2.2.4 on 2019-08-14 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0005_auto_20190813_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='icon',
            field=models.CharField(default='far fa-check-square', help_text='The font-awesome icon string for display in the UI.', max_length=20, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 20, 20, 22, 419956), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
