# Generated by Django 2.2.7 on 2019-12-13 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0009_auto_20191106_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='authentication_info',
            field=models.ForeignKey(blank=True, help_text='The Authentication Info to use when sending transaction data.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quartet_output.AuthenticationInfo', verbose_name='Authentication Info'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='default_owning_party',
            field=models.ForeignKey(blank=True, help_text='The default owning party if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_owning_party', to='quartet_masterdata.Company', verbose_name='Owning Party'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='default_possessing_party',
            field=models.ForeignKey(blank=True, help_text='The default possessing party if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_possessing_party', to='quartet_masterdata.Company', verbose_name='Possessing Party'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='default_ship_from',
            field=models.ForeignKey(blank=True, help_text='The default ship from location.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_ship_from', to='quartet_masterdata.Location', verbose_name='Ship From'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='default_ship_to',
            field=models.ForeignKey(blank=True, help_text='The default location that this transaction will use as a ship-to-location.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_ship_to', to='quartet_masterdata.Location', verbose_name='Ship To'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 18, 26, 22, 387804), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='event_type',
            field=models.CharField(choices=[('OBJECT', 'OBJECT'), ('AGGREGATION', 'AGGREGATION'), ('TRANSACTION', 'TRANSACTION')], default='OBJECT', help_text='The type of EPCIS event to create.', max_length=20, verbose_name='Event Type'),
        ),
    ]
