# Generated by Django 2.2.7 on 2019-12-18 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0010_auto_20191213_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 21, 33, 41, 680231), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
