# Generated by Django 2.2.7 on 2019-12-19 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0011_auto_20191218_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 15, 55, 38, 977259), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
