# Generated by Django 2.2.7 on 2019-12-19 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0012_auto_20191219_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 17, 44, 32, 341733), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
