# Generated by Django 3.0.1 on 2019-12-19 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0013_auto_20191219_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 17, 59, 46, 472751), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
