# Generated by Django 3.0.2 on 2020-02-12 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0014_auto_20191219_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 16, 50, 30, 31241), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
