# Generated by Django 3.0.2 on 2020-04-01 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0015_auto_20200212_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 21, 45, 2, 786842), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
