# Generated by Django 3.0.5 on 2020-08-24 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0016_auto_20200401_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 16, 24, 40, 652530), help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
