# Generated by Django 3.1.1 on 2020-09-29 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warewolf_api', '0017_auto_20200824_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date this transaction was initially created.', verbose_name='Created Date'),
        ),
    ]
